version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: website-ani-laravel
    restart: unless-stopped
    working_dir: /var/www
    expose:
      - 8000
    volumes:
      - .:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: website-ani-nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - laravel

  certbot:
      image: certbot/certbot
      container_name: website-ani-certbot
      volumes: 
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
      command: certonly --webroot -w /var/www/certbot --keep-until-expiring --email aniteknologi@gmail.com -d anitech.id --agree-tos

  db:
    image: mysql:5.7
    container_name: website-ani-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_DATABASE: anitech
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
    driver: local